const dial = "Singapore:65|Afghanistan:93|Albania:355|Algeria:213|Andorra:376|Angola:244|Argentina:54|Armenia:374|Australia:61|Austria:43|Azerbaijan:994|Bahamas:1242|Bahrain:973|Bangladesh:880|Barbados:1246|Belarus:375|Belgium:32|Belize:501|Benin:229|Bhutan:975|Bolivia:591|Bosnia-Herzegovina:387|Botswana:267|Brazil:55|Brunei:673|Bulgaria:359|Burkina Faso:226|Burundi:257|Cambodia:855|Cameroon:237|Canada:1|Chile:56|China:86|Colombia:57|Costa Rica:506|Croatia:385|Cuba:53|Cyprus:357|Czech Republic:420|Denmark:45|Dominican Republic:1809|Ecuador:593|Egypt:20|El Salvador:503|Estonia:372|Ethiopia:251|Fiji Islands:679|Finland:358|France:33|Georgia:995|Germany:49|Ghana:233|Greece:30|Guatemala:502|Honduras:504|Hong Kong:852|Hungary:36|Iceland:354|India:91|Indonesia:62|Iran:98|Iraq:964|Ireland:353|Israel:972|Italy:39|Jamaica:1876|Japan:81|Jordan:962|Kazakhstan:7|Kenya:254|Korea (South):82|Kuwait:965|Kyrgyzstan:996|Laos:856|Latvia:371|Lebanon:961|Lithuania:370|Luxembourg:352|Macau:853|Madagascar:261|Malaysia:60|Maldives:960|Malta:356|Mauritius:230|Mexico:52|Moldova:373|Monaco:377|Mongolia:976|Montenegro:382|Morocco:212|Mozambique:258|Myanmar:95|Namibia:264|Nepal:977|Netherlands:31|New Zealand:64|Nicaragua:505|Nigeria:234|Norway:47|Oman:968|Pakistan:92|Palestine:970|Panama:507|Papua New Guinea:675|Paraguay:595|Peru:51|Philippines:63|Poland:48|Portugal:351|Qatar:974|Romania:40|Russia:7|Rwanda:250|Saudi Arabia:966|Senegal:221|Serbia:381|Seychelles:248|Slovakia:421|Slovenia:386|South Africa:27|Spain:34|Sri Lanka:94|Sudan:249|Sweden:46|Switzerland:41|Syria:963|Taiwan:886|Tajikistan:992|Tanzania:255|Thailand:66|Timor-Leste:670|Tunisia:216|Turkey:90|Turkmenistan:993|Uganda:256|Ukraine:380|United Arab Emirates:971|United Kingdom:44|United States of America:1|Uruguay:598|Uzbekistan:998|Venezuela:58|Vietnam:84|Yemen:967|Zambia:260|Zimbabwe:263";
export const DIAL_CODES = dial.split("|").map(s => { const [name, code] = s.split(":"); return { name: name!, code: code! }; });

const nat = "AFGHAN|ALBANIAN|ALGERIAN|AMERICAN|ANDORRAN|ANGOLAN|ARGENTINEAN|ARMENIAN|AUSTRALIAN|AUSTRIAN|AZERBAIJANI|BAHAMIAN|BAHRAINI|BANGLADESHI|BARBADIAN|BELARUSIAN|BELGIAN|BELIZEAN|BENINESE|BHUTANESE|BOLIVIAN|BOSNIAN|BRAZILIAN|BRITISH|BRUNEIAN|BULGARIAN|BURMESE|BURUNDIAN|CAMBODIAN|CAMEROONIAN|CANADIAN|CHILEAN|CHINESE|COLOMBIAN|CONGOLESE|COSTA RICAN|CROATIAN|CUBAN|CYPRIOT|CZECH|DANISH|DOMINICAN|DUTCH|EAST TIMORESE|ECUADOREAN|EGYPTIAN|EMIRIAN|ESTONIAN|ETHIOPIAN|FIJIAN|FILIPINO|FINNISH|FRENCH|GEORGIAN|GERMAN|GHANAIAN|GREEK|GUATEMALAN|HONDURAN|HUNGARIAN|ICELANDER|INDIAN|INDONESIAN|IRANIAN|IRAQI|IRISH|ISRAELI|ITALIAN|JAMAICAN|JAPANESE|JORDANIAN|KAZAKHSTANI|KENYAN|KUWAITI|KYRGYZ|LAOTIAN|LATVIAN|LEBANESE|LITHUANIAN|LUXEMBOURGER|MACEDONIAN|MALAGASY|MALAYSIAN|MALDIVIAN|MALTESE|MAURITIAN|MEXICAN|MOLDOVAN|MONGOLIAN|MOROCCAN|MOZAMBICAN|NAMIBIAN|NEPALESE|NEW ZEALANDER|NICARAGUAN|NIGERIAN|NORTH KOREAN|NORWEGIAN|OMANI|PAKISTANI|PANAMANIAN|PAPUA NEW GUINEAN|PARAGUAYAN|PERUVIAN|POLISH|PORTUGUESE|QATARI|ROMANIAN|RUSSIAN|RWANDAN|SAUDI|SENEGALESE|SERBIAN|SLOVAKIAN|SLOVENIAN|SOUTH AFRICAN|SOUTH KOREAN|SPANISH|SRI LANKAN|SUDANESE|SWEDISH|SWISS|SYRIAN|TAIWANESE|TAJIK|TANZANIAN|THAI|TUNISIAN|TURKISH|UGANDAN|UKRAINIAN|URUGUAYAN|UZBEKISTANI|VENEZUELAN|VIETNAMESE|YEMENITE|ZAMBIAN|ZIMBABWEAN";
export const NATIONALITIES = ["SINGAPORE CITIZEN", "SINGAPORE PR", "LTVP+", ...nat.split("|")];

export const QUALIFICATIONS = ["No Formal Qualification", "PSLE & Below", "Lower Secondary", "GCE 'N' Level or equivalent", "GCE 'O' Level or equivalent", "GCE 'A' Level or equivalent", "Nitec and Higher Nitec", "Diploma", "Professional Certifications", "Degree", "Post Graduate Diploma", "Master", "Doctorate", "Other Education", "Not Available"];

export const SALES_MANAGERS = ["A Team", "Betty Lee", "BTR", "Crystal Ng", "Dylan Kong", "Harper Kok", "Irene Low", "IT", "Jeff Lim", "Kino Zhang", "Megan Goh", "N Team", "Ng Hong Lan", "Nora Wang", "Shu Hui", "Tiffany Nguyen", "Training Management", "Tyson Low", "Wendyy Chua", "Win Team", "Yvonne Cheng"];

export const APP_STAGES = [["new", "New"], ["contacted", "Contacted"], ["screening", "Screening"], ["offer", "Offer sent"], ["approved", "Approved"], ["enrolled", "Enrolled"], ["closed", "Closed"]] as const;
