import aiImage from "@/assets/course-ai.jpg";
import beautyImage from "@/assets/course-beauty.jpg";
import serviceImage from "@/assets/course-service.jpg";
import diplomaImage from "@/assets/course-diploma.jpg";

export type CourseCategory = "AI & Business" | "Beauty & Wellness" | "Retail & Service" | "Diplomas";

export type Course = {
  slug: string;
  title: string;
  category: CourseCategory;
  summary: string;
  duration: string;
  mode: string;
  price: string;
  badge: string;
  image: string;
  outcomes: string[];
};

const courseImages = import.meta.glob<string>("../assets/courses/*.jpg", { eager: true, import: "default" });
const imageFor = (slug: string, fallback: string) => courseImages[`../assets/courses/${slug}.jpg`] ?? fallback;

const baseCourses: Course[] = [
  {
    slug: "ai-course-singapore",
    title: "Integrated Digital Marketing with Generative AI",
    category: "AI & Business",
    summary: "Step into the future of marketing with this hands-on, 2-day AI marketing course designed for modern creators and business owners. Through interactive lessons and real-world practic...",
    duration: "16 Hrs (2 Days)",
    mode: "Classroom",
    price: "From $216",
    badge: "WSQ",
    image: aiImage,
    outcomes: ["Step into the future of marketing with this hands-on, 2-day AI marketing course designed for modern creators and business owners", "Through interactive lessons and real-world practice, you’ll learn how to use latest Generative AI tools to create stunning and engaging content, images, music, and videos that capture attention and drive results"],
  },
  {
    slug: "brand-management-and-storytelling",
    title: "Brand Management and Storytelling",
    category: "AI & Business",
    summary: "This course equips learners with essential skills to build and communicate brand value through strategic storytelling. Participants will learn to craft compelling brand messages, u...",
    duration: "16 Hrs (2 Days)",
    mode: "Classroom",
    price: "From $300",
    badge: "WSQ",
    image: aiImage,
    outcomes: ["This course equips learners with essential skills to build and communicate brand value through strategic storytelling", "Participants will learn to craft compelling brand messages, understand customer insights, and plan integrated marketing and PR campaigns aligned with brand positioning", "By tracking key performance indicators, learners will evaluate campaign effectiveness and refine strategies to enhance brand visibility and impact"],
  },
  {
    slug: "certificate-in-eyebrow-embroidery",
    title: "Certificate in Eyebrow Embroidery",
    category: "Beauty & Wellness",
    summary: "Master the art of Machine Ombre Brows in this intensive 3-day workshop. Designed for beginners and beauty professionals, this hands-on course equips learners with the essential kno...",
    duration: "18 Hours (3 Days)",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Certificate",
    image: beautyImage,
    outcomes: ["Master the art of Machine Ombre Brows in this intensive 3-day workshop", "Designed for beginners and beauty professionals, this hands-on course equips learners with the essential knowledge, techniques and practical skills to create soft, natural and well-defined ombre brows using professional PMU machines", "Through a combination of theory, trainer demonstrations and practical application, learners will develop skills in brow mapping, machine handling, pigment selection, shading techniques, client consultation and aftercare while following appropriate hygiene and safety practices"],
  },
  {
    slug: "certificate-in-eyelash-extension",
    title: "Certificate in Eyelash Extension",
    category: "Beauty & Wellness",
    summary: "Kickstart your career in the beauty industry with the SOQ Eyelash Extension Course. Designed for beginners, this intensive hands-on programme equips learners with the essential knowl...",
    duration: "12 Hours (2 Days)",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Certificate",
    image: beautyImage,
    outcomes: ["Kickstart your career in the beauty industry with the SOQ Eyelash Extension Course", "Designed for beginners, this intensive hands-on programme equips learners with the essential knowledge and practical skills required to perform professional eyelash extension services confidently and safely", "Through a combination of theory, demonstrations, and practical application, participants will learn the fundamentals of lash artistry, client consultation, lash styling, and application techniques while adhering to industry-standard hygiene and safety practices"],
  },
  {
    slug: "color-concept-application",
    title: "Colour Concept Application",
    category: "Retail & Service",
    summary: "Learners will be able to interpret the use of colour, its attributes and relationship, and apply the colour emotional, cultural and situational aspects in relation to retails industr...",
    duration: "8 Hrs (1 Day)",
    mode: "Classroom",
    price: "From $96",
    badge: "WSQ",
    image: serviceImage,
    outcomes: ["Learners will be able to interpret the use of colour, its attributes and relationship, and apply the colour emotional, cultural and situational aspects in relation to retails industry", "Learners will be able to identify the materials, tools and equipment to experiment colour and understand the effect of colour matching to achieve the desired results", "Learners will be able to review and reflect the use of colour in accordance with safety guidelines and procedures"],
  },
  {
    slug: "dementia-care-and-person-centred-practices",
    title: "Dementia Care and Person-Centred Practices",
    category: "Beauty & Wellness",
    summary: "The Dementia Care and Person-Centred Practices course empowers learners with the knowledge and empathy required to support individuals living with dementia. Participants will gain ...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Dementia Care and Person-Centred Practices course empowers learners with the knowledge and empathy required to support individuals living with dementia", "Participants will gain a strong understanding of dementia’s symptoms, stages, and impact on memory, behaviour, and emotions"],
  },
  {
    slug: "diploma-in-aromatherapy",
    title: "Diploma in Aromatherapy",
    category: "Diplomas",
    summary: "The Diploma in Aromatherapy offers learners the chance to master one of today’s most in-demand wellness skills — the art and science of using essential oils for healing, relaxation...",
    duration: "208 Hrs (8 Months)",
    mode: "Blended Learning",
    price: "From $734.87/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Aromatherapy offers learners the chance to master one of today’s most in-demand wellness skills — the art and science of using essential oils for healing, relaxation, and holistic care", "Through this course, learners will gain both hands-on practical skills and in-depth theoretical knowledge to deliver professional aromatherapy treatments, create personalised blends, and promote overall mind-body balance", "It’s the perfect path for those who wish to build a fulfilling career in the beauty and holistic wellness industry, or start their own wellness practice"],
  },
  {
    slug: "diploma-in-international-business-development",
    title: "Diploma in International Business Development",
    category: "Diplomas",
    summary: "The programme offers students an opportunity to understand the technical know-how about starting and running his or her own business as well as the expectations of employers from emp...",
    duration: "208 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $979.82/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The programme offers students an opportunity to understand the technical know-how about starting and running his or her own business as well as the expectations of employers from employees especially in this ever-changing business dispensation", "This programme does not only deal with local businesses as case study", "It is designed to use the international market scene to challenge students to being proactive, as employees are being give herculean tasks to deliver across various parts of the world irrespective of the challenges they face going across borders"],
  },
  {
    slug: "diploma-in-international-business-development-mandarin",
    title: "Diploma in International Business Development (Mandarin)",
    category: "Diplomas",
    summary: "Diploma in International Business Development (Mandarin) offers students an opportunity to understand the technical know-how about starting and running his or her own business as w...",
    duration: "208 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $979.82/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["Diploma in International Business Development (Mandarin) offers students an opportunity to understand the technical know-how about starting and running his or her own business as well as the expectations of employers from employees especially in this ever-changing business dispensation", "This programme does not only deal with local businesses as case study", "It is designed to use the international market scene to challenge students to being proactive, as employees are being give herculean tasks to deliver across various parts of the world irrespective of the challenges they face going across borders"],
  },
  {
    slug: "diploma-in-international-business-management",
    title: "Diploma in International Business Management",
    category: "Diplomas",
    summary: "This course enables the student adapt into many business portfolios like corporate investments and ventures, operation, accounting, and human capital development and management. It...",
    duration: "208 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $979.82/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["This course enables the student adapt into many business portfolios like corporate investments and ventures, operation, accounting, and human capital development and management", "It will not just be theory every time as students will also participate in solving practical business related issues", "Students will participate in class discussions, group projects, assignments and assessments that are designed to improve their soft skills on how they solve problems, lead, make decisions, manage time, make presentations, work in a team and communicate effectively"],
  },
  {
    slug: "diploma-in-international-business-management-mandarin",
    title: "Diploma in International Business Management (Mandarin)",
    category: "Diplomas",
    summary: "Diploma in International Business Management (Mandarin) enables the student adapt into many business portfolios like corporate investments and ventures, operation, accounting, and ...",
    duration: "208 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $979.82/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["Diploma in International Business Management (Mandarin) enables the student adapt into many business portfolios like corporate investments and ventures, operation, accounting, and human capital development and management", "It will not just be theory every time as students will also participate in solving practical business related issues", "Students will participate in class discussions, group projects, assignments and assessments that are designed to improve their soft skills on how they solve problems, lead, make decisions, manage time, make presentations, work in a team and communicate effectively"],
  },
  {
    slug: "diploma-in-maternal-newborn-and-infant-care",
    title: "Diploma in Maternal, Newborn and Infant Care",
    category: "Diplomas",
    summary: "The Diploma in Maternal, Newborn and Infant Care is designed to equip learners with the essential knowledge, practical skills and professional competencies required to provide safe...",
    duration: "252 Hrs (6 / 9 months)",
    mode: "Blended Learning",
    price: "From $724.85",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Maternal, Newborn and Infant Care is designed to equip learners with the essential knowledge, practical skills and professional competencies required to provide safe, effective and holistic care for mothers, newborns and infants", "The programme covers maternal health, postnatal recovery, newborn care, infant development, breastfeeding support, nutrition, hygiene, safety, communication and professional caregiving practices", "Learners will develop the confidence to support families during the prenatal and postnatal period while applying industry best practices and maintaining high standards of professionalism"],
  },
  {
    slug: "diploma-in-maternal-newborn-and-infant-care-mandarin",
    title: "Diploma in Maternal, Newborn and Infant Care (Mandarin)",
    category: "Diplomas",
    summary: "The Diploma in Maternal, Newborn and Infant Care (Mandarin) is designed to equip learners with the essential knowledge, practical skills and professional competencies required to p...",
    duration: "252 Hrs (6 / 9 months)",
    mode: "Blended Learning",
    price: "From $724.85",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Maternal, Newborn and Infant Care (Mandarin) is designed to equip learners with the essential knowledge, practical skills and professional competencies required to provide safe, effective and holistic care for mothers, newborns and infants", "The programme covers maternal health, postnatal recovery, newborn care, infant development, breastfeeding support, nutrition, hygiene, safety, communication and professional caregiving practices", "Learners will develop the confidence to support families during the prenatal and postnatal period while applying industry best practices and maintaining high standards of professionalism"],
  },
  {
    slug: "diploma-in-professional-eyelash-extension",
    title: "Diploma in Professional Eyelash Extension",
    category: "Diplomas",
    summary: "The Diploma in Professional Eyelash Extension is designed to provide learners with the practical skills and theoretical knowledge required to perform safe, high-quality eyelash ext...",
    duration: "192 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $666.35/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Professional Eyelash Extension is designed to provide learners with the practical skills and theoretical knowledge required to perform safe, high-quality eyelash extension services", "The programme focuses on developing precision, creativity, and professionalism — preparing learners to work as certified lash artists or manage their own lash business in the growing beauty industry"],
  },
  {
    slug: "diploma-in-professional-eyelash-extension-mandarin",
    title: "Diploma in Professional Eyelash Extension (Mandarin)",
    category: "Diplomas",
    summary: "The Diploma in Professional Eyelash Extension (Mandarin) is designed to provide learners with the practical skills and theoretical knowledge required to perform safe, high-quality ...",
    duration: "192 Hrs (6 Months)",
    mode: "Blended Learning",
    price: "From $666.35/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Professional Eyelash Extension (Mandarin) is designed to provide learners with the practical skills and theoretical knowledge required to perform safe, high-quality eyelash extension services", "The programme focuses on developing precision, creativity, and professionalism — preparing learners to work as certified lash artists or manage their own lash business in the growing beauty industry"],
  },
  {
    slug: "diploma-in-professional-make-up",
    title: "Diploma in Professional Make Up",
    category: "Diplomas",
    summary: "The main objective of the Diploma in Professional Make Up is to enable learners to gain the necessary practical skills and knowledge to provide fashion, photographic and media make...",
    duration: "216 Hrs (8 Months)",
    mode: "Blended Learning",
    price: "Enquire for details",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The main objective of the Diploma in Professional Make Up is to enable learners to gain the necessary practical skills and knowledge to provide fashion, photographic and media make-up to the general public and performers and to gain employment in the photography and media make up industry"],
  },
  {
    slug: "diploma-in-semi-permanent-embroidery",
    title: "Diploma in Semi-permanent Embroidery",
    category: "Diplomas",
    summary: "The Diploma in Semi-Permanent Embroidery is designed to equip learners with both practical and theoretical expertise to perform professional eyebrow, eyeliner, and lip embroidery s...",
    duration: "224 Hrs (8 Months)",
    mode: "Blended Learning",
    price: "From $541.25/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Semi-Permanent Embroidery is designed to equip learners with both practical and theoretical expertise to perform professional eyebrow, eyeliner, and lip embroidery services", "The programme focuses on developing precision, artistry, and hygiene standards required to deliver safe, high-quality results to clients"],
  },
  {
    slug: "diploma-in-semi-permanent-embroidery-mandarin",
    title: "Diploma in Semi-permanent Embroidery (Mandarin)",
    category: "Diplomas",
    summary: "The Diploma in Semi-permanent Embroidery (Mandarin) is designed to equip learners with both practical and theoretical expertise to perform professional eyebrow, eyeliner, and lip e...",
    duration: "224 Hrs (8 Months)",
    mode: "Blended Learning",
    price: "From $541.25/mo",
    badge: "Diploma",
    image: diplomaImage,
    outcomes: ["The Diploma in Semi-permanent Embroidery (Mandarin) is designed to equip learners with both practical and theoretical expertise to perform professional eyebrow, eyeliner, and lip embroidery services", "The programme focuses on developing precision, artistry, and hygiene standards required to deliver safe, high-quality results to clients"],
  },
  {
    slug: "effective-communication-for-quality-service-delivery",
    title: "Effective Communication for Quality Service Delivery",
    category: "Retail & Service",
    summary: "This course equips learners with effective communication skills to deliver quality service across diverse customer interactions. Participants will learn how to clarify information,...",
    duration: "8 Hrs (1 Day)",
    mode: "Classroom",
    price: "From $96",
    badge: "WSQ",
    image: serviceImage,
    outcomes: ["This course equips learners with effective communication skills to deliver quality service across diverse customer interactions", "Participants will learn how to clarify information, respond appropriately, and adapt communication styles to different social and cultural backgrounds", "Through practical scenarios and roleplays, learners gain the confidence to apply verbal and non-verbal communication that builds trust, enhances customer satisfaction, and drives positive results in the workplace"],
  },
  {
    slug: "effective-product-demonstration",
    title: "Effective Product Demonstration",
    category: "Retail & Service",
    summary: "This course emphasizes the importance of performing effective product demonstrations based on the types of information about the products and services to be presented in retail ind...",
    duration: "16 Hrs (2 Days)",
    mode: "Classroom",
    price: "From $150",
    badge: "WSQ",
    image: serviceImage,
    outcomes: ["This course emphasizes the importance of performing effective product demonstrations based on the types of information about the products and services to be presented in retail industry", "Learners become effective in performing product demonstrations when they apply competently the different methods of demonstration while probing for customer’s requirements using effective communication skills"],
  },
  {
    slug: "fundamental-of-foot-massage",
    title: "Fundamental of Foot massage",
    category: "Beauty & Wellness",
    summary: "The Fundamental of Foot Massage course introduces the essential theories and practical techniques of foot wellness therapy. Learners will gain a deep understanding of foot anatomy,...",
    duration: "4 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Fundamental of Foot Massage course introduces the essential theories and practical techniques of foot wellness therapy", "Learners will gain a deep understanding of foot anatomy, reflex zones, and pressure points connected to various organs and systems of the body"],
  },
  {
    slug: "fundamental-of-hand-massage",
    title: "Fundamental of Hand massage",
    category: "Beauty & Wellness",
    summary: "The Fundamental of Hand Massage course introduces learners to the art and science of therapeutic hand care — a simple yet powerful wellness practice that promotes relaxation, circu...",
    duration: "4 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Fundamental of Hand Massage course introduces learners to the art and science of therapeutic hand care — a simple yet powerful wellness practice that promotes relaxation, circulation, and emotional balance", "Through theory and guided practice, learners will explore the anatomy of the hand, key reflex zones, and effective massage techniques that ease muscle tension and enhance overall well-being"],
  },
  {
    slug: "head-shoulder-meridian-bojin",
    title: "Head & Shoulder Meridian (Bojin)",
    category: "Beauty & Wellness",
    summary: "The Healthy Head & Shoulder Meridian (Bojin) course introduces learners to a holistic therapy that targets all key meridian channels and acupoints across the head, neck, and should...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Healthy Head & Shoulder Meridian (Bojin) course introduces learners to a holistic therapy that targets all key meridian channels and acupoints across the head, neck, and shoulders", "This rejuvenating treatment focuses on restoring energy flow, relieving muscle tension, and improving overall circulation", "By addressing physical, hormonal, and emotional imbalances, it promotes relaxation, mental clarity, and a renewed sense of well-being"],
  },
  {
    slug: "healthy-body-meridian-bojin",
    title: "Healthy Body Meridian (Bojin)",
    category: "Beauty & Wellness",
    summary: "By addressing common problem areas such as the hands, legs, back, and abdomen, this course teaches learners how to release blockages, improve circulation, and restore the body’s na...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["By addressing common problem areas such as the hands, legs, back, and abdomen, this course teaches learners how to release blockages, improve circulation, and restore the body’s natural vitality", "Blending traditional healing wisdom with modern application, it provides a transformative approach to whole-body rejuvenation and overall well-being"],
  },
  {
    slug: "healthy-face-meridian-bojin",
    title: "Healthy Face Meridian (Bojin)",
    category: "Beauty & Wellness",
    summary: "This comprehensive programme delivers 4-in-1 skill mastery, covering techniques for the face, eyes, neck, and full Songjin therapy. It provides a complete toolkit to rejuvenate and r...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["This comprehensive programme delivers 4-in-1 skill mastery, covering techniques for the face, eyes, neck, and full Songjin therapy", "It provides a complete toolkit to rejuvenate and restore skin health from the inside out — blending ancient healing principles with modern expertise to reveal radiant, healthy, and youthful-looking skin"],
  },
  {
    slug: "image-consultant-master-class",
    title: "Image Consultant Master Class",
    category: "Beauty & Wellness",
    summary: "The Image Consultant Master Class is a comprehensive programme designed to equip learners with the expertise to transform personal and professional presence. Beyond the fundamentals ...",
    duration: "8 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Image Consultant Master Class is a comprehensive programme designed to equip learners with the expertise to transform personal and professional presence", "Beyond the fundamentals of personal makeup, this course dives into colour and style mastery, wardrobe planning, etiquette and communication, personal branding, and grooming strategies"],
  },
  {
    slug: "infant-care-and-wellness",
    title: "Infant Care and Wellness",
    category: "Beauty & Wellness",
    summary: "The Infant Care and Wellness course equips learners with essential knowledge and hands-on skills to care for infants safely, confidently, and compassionately. Participants will gai...",
    duration: "4 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Infant Care and Wellness course equips learners with essential knowledge and hands-on skills to care for infants safely, confidently, and compassionately", "Participants will gain a strong understanding of infant growth, development, and daily care routines — from feeding and bathing to hygiene, comfort, and communication"],
  },
  {
    slug: "infant-massage",
    title: "Infant Massage",
    category: "Beauty & Wellness",
    summary: "The Infant Massage Course provides essential knowledge and hands-on skills for promoting healthy growth, emotional bonding, and overall wellness in infants. Rooted in developmental...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Infant Massage Course provides essential knowledge and hands-on skills for promoting healthy growth, emotional bonding, and overall wellness in infants", "Rooted in developmental touch therapy, the course teaches safe and nurturing techniques that support babies’ physical, emotional, and sensory development while helping caregivers build deeper connections through touch"],
  },
  {
    slug: "japan-face-lifting",
    title: "Japan Face Lifting",
    category: "Beauty & Wellness",
    summary: "The Japan Face Lifting Workshop introduces learners to the art of Japanese-style V-shaped facial sculpting techniques that combine traditional lifting principles with modern aesthe...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Japan Face Lifting Workshop introduces learners to the art of Japanese-style V-shaped facial sculpting techniques that combine traditional lifting principles with modern aesthetics", "This non-invasive, non-surgical method focuses on improving facial symmetry, defining contours, and enhancing skin vitality through specialised hand techniques"],
  },
  {
    slug: "keratin-lash-lift",
    title: "Keratin Lash Lift",
    category: "Beauty & Wellness",
    summary: "The Keratin Lash Lift Course is a hands-on training programme designed to equip learners with professional techniques to enhance, curl, and nourish natural lashes using safe, non-inv...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Keratin Lash Lift Course is a hands-on training programme designed to equip learners with professional techniques to enhance, curl, and nourish natural lashes using safe, non-invasive methods", "Unlike traditional lash perming, this advanced keratin-based treatment lifts and strengthens the lashes while keeping them soft, glossy, and damage-free"],
  },
  {
    slug: "korea-lymph-detoxification-guasha",
    title: "Korea Lymph Detoxification (Guasha)",
    category: "Beauty & Wellness",
    summary: "The Korea Lymph Detoxification (Guasha) course introduces learners to an advanced, holistic approach to facial and body detoxification rooted in Korean wellness practices. This tra...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Korea Lymph Detoxification (Guasha) course introduces learners to an advanced, holistic approach to facial and body detoxification rooted in Korean wellness practices", "This training focuses on promoting healthy lymphatic flow to support natural healing, reduce puffiness, and improve skin clarity"],
  },
  {
    slug: "make-up-master-class",
    title: "Professional Make Up Master Class",
    category: "Beauty & Wellness",
    summary: "The Makeup Master Class is an advanced programme designed for those ready to take their artistry to a professional level. Building on the fundamentals of personal makeup, this course...",
    duration: "12 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Makeup Master Class is an advanced programme designed for those ready to take their artistry to a professional level", "Building on the fundamentals of personal makeup, this course equips learners with skills in client-ready day and evening looks, photography and stage makeup, creative hairstyling, and extensive live model practice"],
  },
  {
    slug: "pelvic-wellness-care",
    title: "Pelvic Wellness Care",
    category: "Beauty & Wellness",
    summary: "The Pelvic Wellness Care course is designed to help women regain physical strength, confidence, and balance through specialised wellness care rooted in advanced Japanese pelvic the...",
    duration: "4 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Pelvic Wellness Care course is designed to help women regain physical strength, confidence, and balance through specialised wellness care rooted in advanced Japanese pelvic therapy techniques", "This holistic training focuses on improving pelvic floor strength, posture alignment, and overall vitality — addressing concerns such as postnatal recovery, hormonal changes, lower back pain, and core weakness"],
  },
  {
    slug: "personal-make-up",
    title: "Personal Make Up",
    category: "Beauty & Wellness",
    summary: "The Personal Makeup Basic Course introduces learners to the fundamentals of everyday beauty. You’ll learn how to identify your skin tone, prep your skin, select suitable products, ...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Personal Makeup Basic Course introduces learners to the fundamentals of everyday beauty", "You’ll learn how to identify your skin tone, prep your skin, select suitable products, and apply makeup with the right tools for a fresh, natural finish"],
  },
  {
    slug: "postnatal-care-and-recovery-for-mothers",
    title: "Postnatal Care and Recovery for mothers",
    category: "Beauty & Wellness",
    summary: "The Postnatal Care and Recovery for Mothers course provides essential knowledge and practical insights into supporting women’s physical and emotional recovery after childbirth. Lea...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Postnatal Care and Recovery for Mothers course provides essential knowledge and practical insights into supporting women’s physical and emotional recovery after childbirth", "Learners will explore the physiological and hormonal changes that occur post-delivery and gain an understanding of how to manage fatigue, body discomfort, and emotional well-being through safe and holistic care methods"],
  },
  {
    slug: "postnatal-nutrition-for-mothers",
    title: "Postnatal Nutrition for Mothers",
    category: "Beauty & Wellness",
    summary: "The Postnatal Nutrition for Mothers course focuses on the vital role of nutrition in a mother’s physical recovery, hormonal balance, and lactation after childbirth. Learners will g...",
    duration: "2 Sessions",
    mode: "Classroom",
    price: "Enquire for details",
    badge: "Workshop",
    image: beautyImage,
    outcomes: ["The Postnatal Nutrition for Mothers course focuses on the vital role of nutrition in a mother’s physical recovery, hormonal balance, and lactation after childbirth", "Learners will gain a deep understanding of how proper diet planning supports healing, boosts energy, and promotes healthy milk production"],
  },
  {
    slug: "product-advisory-skills-for-the-beauty-care-industry",
    title: "Product Advisory Skills For The Beauty Care industry",
    category: "Retail & Service",
    summary: "Enhance your expertise in beauty care products and customer consultation. Learn how to identify client needs, recommend suitable products, and present them professionally to boost ...",
    duration: "16 Hrs (2 Days)",
    mode: "Classroom",
    price: "From $150",
    badge: "WSQ",
    image: serviceImage,
    outcomes: ["Enhance your expertise in beauty care products and customer consultation", "Learn how to identify client needs, recommend suitable products, and present them professionally to boost trust and sales", "This practical course also covers communication, product demonstration, and sales closure techniques — empowering you to become a confident, knowledgeable beauty adviser who elevates both customer experience and brand image"],
  },
  {
    slug: "vtct-skills-itec-level-3-diploma-in-fashion-theatre-and-media-make-up",
    title: "VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up",
    category: "Diplomas",
    summary: "The VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up equips learners with the practical skills, technical knowledge and professional competencies required t...",
    duration: "306 Hrs (6 / 10 Months)",
    mode: "Blended",
    price: "From $798.10/mo",
    badge: "VTCT",
    image: diplomaImage,
    outcomes: ["The VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up equips learners with the practical skills, technical knowledge and professional competencies required to deliver fashion, theatrical and media make-up services, including an understanding of skin structure, common skin conditions, client consultation and safety, while developing essential workplace skills such as communication, teamwork, problem-solving and professional practice to pursue a successful career as a make-up artist"],
  },
  {
    slug: "vtct-skills-itec-level-3-diploma-in-fashion-theatre-and-media-make-up-mandarin",
    title: "VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up (Mandarin)",
    category: "Diplomas",
    summary: "The VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up (Mandarin) equips learners with the practical skills, technical knowledge and professional competencies...",
    duration: "306 Hrs (6 / 10 Months)",
    mode: "Blended",
    price: "From $798.10/mo",
    badge: "VTCT",
    image: diplomaImage,
    outcomes: ["The VTCT Skills (ITEC) Level 3 Diploma in Fashion, Theatre and Media Make-up (Mandarin) equips learners with the practical skills, technical knowledge and professional competencies required to deliver fashion, theatrical and media make-up services, including an understanding of skin structure, common skin conditions, client consultation and safety, while developing essential workplace skills such as communication, teamwork, problem-solving and professional practice to pursue a successful career as a make-up artist"],
  },
];

export const courses: Course[] = baseCourses.map(c => ({ ...c, image: imageFor(c.slug, c.image) }));


export const categories = [
  { name: "AI & Business", copy: "Work smarter and grow with technology.", image: aiImage },
  { name: "Beauty & Wellness", copy: "Build professional, hands-on expertise.", image: beautyImage },
  { name: "Retail & Service", copy: "Strengthen customer-facing skills.", image: serviceImage },
  { name: "Diplomas", copy: "Go deeper with structured learning.", image: diplomaImage },
] as const;

export const contact = {
  address: "10 Anson Road, International Plaza, #23-08 & #35-16, Singapore 079903",
  phone: "+65 6996 3383",
  email: "academy@soq.edu.sg",
  whatsapp: "https://wa.me/6587182308",
  portal: "https://soq.trainingsystemsg.com/TMS/login",
};