import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/page-hero";
import { ContactBand, NumberGrid, TextSection } from "@/components/content-sections";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About SOQ International Academy" }, { name: "description", content: "Learn about SOQ International Academy, our values, training approach and Singapore learning facilities." }, { property: "og:title", content: "About SOQ International Academy" }, { property: "og:description", content: "Practical learning, experienced trainers and a learner-centred approach." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });
function AboutPage(){return <><PageHero eyebrow="About SOQ" title="Skills that create brighter possibilities." intro="Since 2013, SOQ International Academy has helped adults and businesses build practical capabilities for a changing world."/><TextSection eyebrow="Our philosophy" title="Learn for the future"><p>We believe effective training should be relevant, practical and empowering. Our programmes connect industry knowledge with hands-on application so learners can act with confidence beyond the classroom.</p><div className="mt-8"><NumberGrid items={[{number:"01",title:"Learner-centred",copy:"Clear support and thoughtful learning experiences for different goals."},{number:"02",title:"Industry relevant",copy:"Practical content shaped around real work and current expectations."},{number:"03",title:"Committed to quality",copy:"Integrity, excellence and continuous improvement guide our work."}]}/></div></TextSection><TextSection tone="soft" eyebrow="Our academy" title="A central place to learn"><p>Our training rooms are located at International Plaza, near Tanjong Pagar MRT. Facilities support focused classroom and blended learning, with class sizes designed for meaningful trainer interaction.</p><Button asChild variant="outline" className="mt-7 rounded-full"><Link to="/trainers">Meet our trainers <ArrowRight/></Link></Button></TextSection><ContactBand/></>}
