import { createFileRoute } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ContactBand, TextSection } from "@/components/content-sections";

export const Route = createFileRoute("/funding")({ head: () => ({ meta: [
  { title: "Course Funding | SOQ International Academy" }, { name: "description", content: "Understand SkillsFuture, WSQ and employer training support for eligible SOQ courses." }, { property: "og:title", content: "Course Funding | SOQ" }, { property: "og:description", content: "Explore available support for individual and company-sponsored training." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: FundingPage });
const schemes = [{title:"Self-sponsored learners",copy:"Eligible Singapore Citizens and Permanent Residents may receive subsidies on selected WSQ programmes. SkillsFuture Credit may also be used by eligible Singapore Citizens."},{title:"Company-sponsored learners",copy:"Eligible employers may access enhanced training support, absentee payroll support and other enterprise schemes."},{title:"Diploma instalment options",copy:"Courses that are not government-funded may offer flexible instalment arrangements. Confirm the latest schedule with our advisers."}];
function FundingPage(){return <><PageHero eyebrow="Funding" title="Make your learning investment count." intro="Course subsidies and credits can make professional development more accessible for individuals and businesses."/><TextSection eyebrow="Available support" title="Funding depends on you and your course"><div className="grid gap-5 md:grid-cols-3">{schemes.map(s=><article key={s.title} className="rounded-lg border border-border p-6"><Check className="size-6 text-brand-gold"/><h3 className="mt-5 font-serif text-2xl text-primary">{s.title}</h3><p className="mt-3 text-sm leading-6">{s.copy}</p></article>)}</div><p className="mt-8 text-sm">Funding rules, eligibility and fees may change. Final eligibility is subject to the relevant authority’s assessment and SOQ’s confirmed fee advice.</p></TextSection><ContactBand/></>}
