/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BookRouteImport } from './routes/book'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CorporateTrainingRouteImport } from './routes/corporate-training'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as JobMatchingRouteImport } from './routes/job-matching'
import { Route as JobMatchingProgramRouteImport } from './routes/job-matching-program'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as LiveClassesRouteImport } from './routes/live-classes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeiProfileRouteImport } from './routes/pei-profile'
import { Route as PortalAdminRouteImport } from './routes/portal-admin'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StaffCoursesRouteImport } from './routes/staff-courses'
import { Route as StudentPoliciesRouteImport } from './routes/student-policies'
import { Route as StudentPortalRouteImport } from './routes/student-portal'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as TutorFinderRouteImport } from './routes/tutor-finder'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as ApiCourseChatRouteImport } from './routes/api/course-chat'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityGuidelinesRouteImport } from './routes/community.guidelines'
import { Route as CommunityMembersRouteImport } from './routes/community.members'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as CommunitySavedRouteImport } from './routes/community.saved'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as TrainerListRouteImport } from './routes/trainer.list'
import { Route as CommunityLiveIndexRouteImport } from './routes/community.live.index'
import { Route as CommunityLiveIdRouteImport } from './routes/community.live.$id'
import { Route as CommunityPostIdRouteImport } from './routes/community.post.$id'
import { Route as CommunityUUsernameRouteImport } from './routes/community.u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTrainingRoute = CorporateTrainingRouteImport.update({
  id: '/corporate-training',
  path: '/corporate-training',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchingRoute = JobMatchingRouteImport.update({
  id: '/job-matching',
  path: '/job-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchingProgramRoute = JobMatchingProgramRouteImport.update({
  id: '/job-matching-program',
  path: '/job-matching-program',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassesRoute = LiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeiProfileRoute = PeiProfileRouteImport.update({
  id: '/pei-profile',
  path: '/pei-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal-admin',
  path: '/portal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCoursesRoute = StaffCoursesRouteImport.update({
  id: '/staff-courses',
  path: '/staff-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPoliciesRoute = StudentPoliciesRouteImport.update({
  id: '/student-policies',
  path: '/student-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorFinderRoute = TutorFinderRouteImport.update({
  id: '/tutor-finder',
  path: '/tutor-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseChatRoute = ApiCourseChatRouteImport.update({
  id: '/api/course-chat',
  path: '/api/course-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community/guidelines',
  path: '/community/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMembersRoute = CommunityMembersRouteImport.update({
  id: '/community/members',
  path: '/community/members',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/community/new',
  path: '/community/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySavedRoute = CommunitySavedRouteImport.update({
  id: '/community/saved',
  path: '/community/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerListRoute = TrainerListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => TrainerRoute,
} as any)
const CommunityLiveIndexRoute = CommunityLiveIndexRouteImport.update({
  id: '/community/live/',
  path: '/community/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLiveIdRoute = CommunityLiveIdRouteImport.update({
  id: '/community/live/$id',
  path: '/community/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/post/$id',
  path: '/community/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityUUsernameRoute = CommunityUUsernameRouteImport.update({
  id: '/community/u/$username',
  path: '/community/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/book': typeof BookRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/funding': typeof FundingRoute
  '/job-matching': typeof JobMatchingRoute
  '/job-matching-program': typeof JobMatchingProgramRoute
  '/join-us': typeof JoinUsRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/pei-profile': typeof PeiProfileRoute
  '/portal-admin': typeof PortalAdminRoute
  '/recommend': typeof RecommendRoute
  '/resources': typeof ResourcesRoute
  '/staff-courses': typeof StaffCoursesRoute
  '/student-policies': typeof StudentPoliciesRoute
  '/student-portal': typeof StudentPortalRoute
  '/teach': typeof TeachRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainers': typeof TrainersRoute
  '/tutor-finder': typeof TutorFinderRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/api/course-chat': typeof ApiCourseChatRoute
  '/community/guidelines': typeof CommunityGuidelinesRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/new': typeof CommunityNewRoute
  '/community/saved': typeof CommunitySavedRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/trainer/list': typeof TrainerListRoute
  '/community/': typeof CommunityIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/community/live/$id': typeof CommunityLiveIdRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
  '/community/live/': typeof CommunityLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/book': typeof BookRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/funding': typeof FundingRoute
  '/job-matching': typeof JobMatchingRoute
  '/job-matching-program': typeof JobMatchingProgramRoute
  '/join-us': typeof JoinUsRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/pei-profile': typeof PeiProfileRoute
  '/portal-admin': typeof PortalAdminRoute
  '/recommend': typeof RecommendRoute
  '/resources': typeof ResourcesRoute
  '/staff-courses': typeof StaffCoursesRoute
  '/student-policies': typeof StudentPoliciesRoute
  '/student-portal': typeof StudentPortalRoute
  '/teach': typeof TeachRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainers': typeof TrainersRoute
  '/tutor-finder': typeof TutorFinderRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/api/course-chat': typeof ApiCourseChatRoute
  '/community/guidelines': typeof CommunityGuidelinesRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/new': typeof CommunityNewRoute
  '/community/saved': typeof CommunitySavedRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/trainer/list': typeof TrainerListRoute
  '/community': typeof CommunityIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/community/live/$id': typeof CommunityLiveIdRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
  '/community/live': typeof CommunityLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/book': typeof BookRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/funding': typeof FundingRoute
  '/job-matching': typeof JobMatchingRoute
  '/job-matching-program': typeof JobMatchingProgramRoute
  '/join-us': typeof JoinUsRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/pei-profile': typeof PeiProfileRoute
  '/portal-admin': typeof PortalAdminRoute
  '/recommend': typeof RecommendRoute
  '/resources': typeof ResourcesRoute
  '/staff-courses': typeof StaffCoursesRoute
  '/student-policies': typeof StudentPoliciesRoute
  '/student-portal': typeof StudentPortalRoute
  '/teach': typeof TeachRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainers': typeof TrainersRoute
  '/tutor-finder': typeof TutorFinderRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/api/course-chat': typeof ApiCourseChatRoute
  '/community/guidelines': typeof CommunityGuidelinesRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/new': typeof CommunityNewRoute
  '/community/saved': typeof CommunitySavedRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/trainer/list': typeof TrainerListRoute
  '/community/': typeof CommunityIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/community/live/$id': typeof CommunityLiveIdRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/community/u/$username': typeof CommunityUUsernameRoute
  '/community/live/': typeof CommunityLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/book'
    | '/businesses'
    | '/calendar'
    | '/careers'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/contact-us'
    | '/corporate-training'
    | '/courses'
    | '/events'
    | '/faq'
    | '/funding'
    | '/job-matching'
    | '/job-matching-program'
    | '/join-us'
    | '/live-classes'
    | '/login'
    | '/pei-profile'
    | '/portal-admin'
    | '/recommend'
    | '/resources'
    | '/staff-courses'
    | '/student-policies'
    | '/student-portal'
    | '/teach'
    | '/trainer'
    | '/trainers'
    | '/tutor-finder'
    | '/verify-certificate'
    | '/api/course-chat'
    | '/community/guidelines'
    | '/community/members'
    | '/community/new'
    | '/community/saved'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/p/$slug'
    | '/trainer/list'
    | '/community/'
    | '/courses/'
    | '/community/live/$id'
    | '/community/post/$id'
    | '/community/u/$username'
    | '/community/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/book'
    | '/businesses'
    | '/calendar'
    | '/careers'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/contact-us'
    | '/corporate-training'
    | '/events'
    | '/faq'
    | '/funding'
    | '/job-matching'
    | '/job-matching-program'
    | '/join-us'
    | '/live-classes'
    | '/login'
    | '/pei-profile'
    | '/portal-admin'
    | '/recommend'
    | '/resources'
    | '/staff-courses'
    | '/student-policies'
    | '/student-portal'
    | '/teach'
    | '/trainer'
    | '/trainers'
    | '/tutor-finder'
    | '/verify-certificate'
    | '/api/course-chat'
    | '/community/guidelines'
    | '/community/members'
    | '/community/new'
    | '/community/saved'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/p/$slug'
    | '/trainer/list'
    | '/community'
    | '/courses'
    | '/community/live/$id'
    | '/community/post/$id'
    | '/community/u/$username'
    | '/community/live'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/book'
    | '/businesses'
    | '/calendar'
    | '/careers'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/contact-us'
    | '/corporate-training'
    | '/courses'
    | '/events'
    | '/faq'
    | '/funding'
    | '/job-matching'
    | '/job-matching-program'
    | '/join-us'
    | '/live-classes'
    | '/login'
    | '/pei-profile'
    | '/portal-admin'
    | '/recommend'
    | '/resources'
    | '/staff-courses'
    | '/student-policies'
    | '/student-portal'
    | '/teach'
    | '/trainer'
    | '/trainers'
    | '/tutor-finder'
    | '/verify-certificate'
    | '/api/course-chat'
    | '/community/guidelines'
    | '/community/members'
    | '/community/new'
    | '/community/saved'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/p/$slug'
    | '/trainer/list'
    | '/community/'
    | '/courses/'
    | '/community/live/$id'
    | '/community/post/$id'
    | '/community/u/$username'
    | '/community/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  BookRoute: typeof BookRoute
  BusinessesRoute: typeof BusinessesRoute
  CalendarRoute: typeof CalendarRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  CorporateTrainingRoute: typeof CorporateTrainingRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  FundingRoute: typeof FundingRoute
  JobMatchingRoute: typeof JobMatchingRoute
  JobMatchingProgramRoute: typeof JobMatchingProgramRoute
  JoinUsRoute: typeof JoinUsRoute
  LiveClassesRoute: typeof LiveClassesRoute
  LoginRoute: typeof LoginRoute
  PeiProfileRoute: typeof PeiProfileRoute
  PortalAdminRoute: typeof PortalAdminRoute
  RecommendRoute: typeof RecommendRoute
  ResourcesRoute: typeof ResourcesRoute
  StaffCoursesRoute: typeof StaffCoursesRoute
  StudentPoliciesRoute: typeof StudentPoliciesRoute
  StudentPortalRoute: typeof StudentPortalRoute
  TeachRoute: typeof TeachRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  TrainersRoute: typeof TrainersRoute
  TutorFinderRoute: typeof TutorFinderRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  ApiCourseChatRoute: typeof ApiCourseChatRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CommunityMembersRoute: typeof CommunityMembersRoute
  CommunityNewRoute: typeof CommunityNewRoute
  CommunitySavedRoute: typeof CommunitySavedRoute
  LearnSlugRoute: typeof LearnSlugRoute
  PSlugRoute: typeof PSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityLiveIdRoute: typeof CommunityLiveIdRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityUUsernameRoute: typeof CommunityUUsernameRoute
  CommunityLiveIndexRoute: typeof CommunityLiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-training': {
      id: '/corporate-training'
      path: '/corporate-training'
      fullPath: '/corporate-training'
      preLoaderRoute: typeof CorporateTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-matching': {
      id: '/job-matching'
      path: '/job-matching'
      fullPath: '/job-matching'
      preLoaderRoute: typeof JobMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-matching-program': {
      id: '/job-matching-program'
      path: '/job-matching-program'
      fullPath: '/job-matching-program'
      preLoaderRoute: typeof JobMatchingProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-classes': {
      id: '/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof LiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pei-profile': {
      id: '/pei-profile'
      path: '/pei-profile'
      fullPath: '/pei-profile'
      preLoaderRoute: typeof PeiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-admin': {
      id: '/portal-admin'
      path: '/portal-admin'
      fullPath: '/portal-admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-courses': {
      id: '/staff-courses'
      path: '/staff-courses'
      fullPath: '/staff-courses'
      preLoaderRoute: typeof StaffCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-policies': {
      id: '/student-policies'
      path: '/student-policies'
      fullPath: '/student-policies'
      preLoaderRoute: typeof StudentPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor-finder': {
      id: '/tutor-finder'
      path: '/tutor-finder'
      fullPath: '/tutor-finder'
      preLoaderRoute: typeof TutorFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-chat': {
      id: '/api/course-chat'
      path: '/api/course-chat'
      fullPath: '/api/course-chat'
      preLoaderRoute: typeof ApiCourseChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/guidelines': {
      id: '/community/guidelines'
      path: '/community/guidelines'
      fullPath: '/community/guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/members': {
      id: '/community/members'
      path: '/community/members'
      fullPath: '/community/members'
      preLoaderRoute: typeof CommunityMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/saved': {
      id: '/community/saved'
      path: '/community/saved'
      fullPath: '/community/saved'
      preLoaderRoute: typeof CommunitySavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/list': {
      id: '/trainer/list'
      path: '/list'
      fullPath: '/trainer/list'
      preLoaderRoute: typeof TrainerListRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/community/live/': {
      id: '/community/live/'
      path: '/community/live'
      fullPath: '/community/live/'
      preLoaderRoute: typeof CommunityLiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/live/$id': {
      id: '/community/live/$id'
      path: '/community/live/$id'
      fullPath: '/community/live/$id'
      preLoaderRoute: typeof CommunityLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/post/$id': {
      id: '/community/post/$id'
      path: '/community/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/u/$username': {
      id: '/community/u/$username'
      path: '/community/u/$username'
      fullPath: '/community/u/$username'
      preLoaderRoute: typeof CommunityUUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface TrainerRouteChildren {
  TrainerListRoute: typeof TrainerListRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerListRoute: TrainerListRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  BookRoute: BookRoute,
  BusinessesRoute: BusinessesRoute,
  CalendarRoute: CalendarRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  CorporateTrainingRoute: CorporateTrainingRoute,
  CoursesRoute: CoursesRouteWithChildren,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  FundingRoute: FundingRoute,
  JobMatchingRoute: JobMatchingRoute,
  JobMatchingProgramRoute: JobMatchingProgramRoute,
  JoinUsRoute: JoinUsRoute,
  LiveClassesRoute: LiveClassesRoute,
  LoginRoute: LoginRoute,
  PeiProfileRoute: PeiProfileRoute,
  PortalAdminRoute: PortalAdminRoute,
  RecommendRoute: RecommendRoute,
  ResourcesRoute: ResourcesRoute,
  StaffCoursesRoute: StaffCoursesRoute,
  StudentPoliciesRoute: StudentPoliciesRoute,
  StudentPortalRoute: StudentPortalRoute,
  TeachRoute: TeachRoute,
  TrainerRoute: TrainerRouteWithChildren,
  TrainersRoute: TrainersRoute,
  TutorFinderRoute: TutorFinderRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  ApiCourseChatRoute: ApiCourseChatRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CommunityMembersRoute: CommunityMembersRoute,
  CommunityNewRoute: CommunityNewRoute,
  CommunitySavedRoute: CommunitySavedRoute,
  LearnSlugRoute: LearnSlugRoute,
  PSlugRoute: PSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityLiveIdRoute: CommunityLiveIdRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityUUsernameRoute: CommunityUUsernameRoute,
  CommunityLiveIndexRoute: CommunityLiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
